-- AchievementConfig.lua
-- Generated by ConfigExporter. Any custom code will be overwritten.

---@class AchievementConfig
---@field Data table<string, table>

---@type AchievementConfig
local AchievementConfig = {Data = {}}

-- --- AUTO GENERATED CONFIG BEGIN ---
AchievementConfig.Data = {
    ['重生'] = {
      ['名字'] = '重生',
      ['类型'] = '天赋成就',
      ['描述'] = '重生栏位',
      ['图标'] = '',
      ['解锁条件'] = {
      },
      ['解锁奖励'] = {
      },
      ['最大等级'] = 20,
      ['升级条件'] = {
        {
          ['消耗物品'] = '奖杯',
          ['消耗数量'] = '',
        },
        {
          ['消耗物品'] = nil,
          ['消耗数量'] = '',
        },
      },
      ['等级效果'] = {
        {
          ['效果类型'] = '玩家变量',
          ['效果字段名称'] = '解锁_重生',
          ['效果数值'] = 'T_LVL*2+1',
          ['效果描述'] = '重生栏位增加，T_LVL是天赋等级',
        },
      },
    },
}
-- --- AUTO GENERATED CONFIG END ---

return AchievementConfig
