-- ActionCostConfig.lua
-- Generated by ConfigExporter. Any custom code will be overwritten.

---@class ActionCostConfig
---@field Data table<string, table>

---@type ActionCostConfig
local ActionCostConfig = {Data = {}}

-- --- AUTO GENERATED CONFIG BEGIN ---
ActionCostConfig.Data = {
    ['重生栏位配置'] = {
      ['配置类型'] = '天赋',
      ['配置名称'] = '重生',
      ['消耗列表'] = {
        {
          ['消耗类型'] = '玩家变量',
          ['消耗名称'] = '数据_固定值_战力值',
          ['数量分段'] = {
            {
              ['条件'] = '0 <= $数据_固定值_历史最大战力值$ < 1000000000',
              ['公式'] = '$数据_固定值_重生次数$*4000',
            },
            {
              ['条件'] = '$数据_固定值_历史最大战力值$ >= 1000000000',
              ['公式'] = '$数据_固定值_重生次数$*5000',
            },
          },
        },
      },
      ['作用目标列表'] = {
        {
          ['目标类型'] = '玩家变量',
          ['目标名称'] = '加成_百分比_训练加成',
          ['作用数值'] = 0.1,
        },
        {
          ['目标类型'] = '玩家变量',
          ['目标名称'] = '数据_固定值_重生次数',
          ['作用数值'] = 1,
        },
      },
    },
}
-- --- AUTO GENERATED CONFIG END ---

return ActionCostConfig
