-- ActionCostConfig.lua
-- Generated by ConfigExporter. Any custom code will be overwritten.

---@class ActionCostConfig
---@field Data table<string, table>

---@type ActionCostConfig
local ActionCostConfig = {Data = {}}

-- --- AUTO GENERATED CONFIG BEGIN ---
ActionCostConfig.Data = {
    ['重生栏位配置'] = {
      ['配置类型'] = '天赋',
      ['配置名称'] = nil,
      ['消耗列表'] = {
        {
          ['消耗类型'] = '玩家变量',
          ['变量来源'] = '玩家变量',
          ['消耗名称'] = '数据_固定值_战力值',
          ['数量分段'] = {
            {
              ['条件'] = '0<$数据_固定值_历史最大战力值$<1000000000',
              ['公式'] = '$数据_固定值_重生次数$*4000',
            },
            {
              ['条件'] = '$数据_固定值_历史最大战力值$>=1000000000',
              ['公式'] = '$数据_固定值_重生次数$*5000',
            },
          },
        },
      },
    },
}
-- --- AUTO GENERATED CONFIG END ---

return ActionCostConfig
