-- EffectTypeConfig.lua
-- Generated by ConfigExporter. Any custom code will be overwritten.

---@class EffectTypeConfig
---@field Data table<string, table>

---@type EffectTypeConfig
local EffectTypeConfig = {Data = {}}

-- --- AUTO GENERATED CONFIG BEGIN ---
EffectTypeConfig.Data = {
    ["加速特效"] = {
        ["特效名"] = "加速特效",
        ["特效预制体"] = nil,
        ["持续时间"] = 0,
        ["跟随目标"] = false,
        ["位置偏移"] = {
            0,
            0,
            0,
        },
        ["旋转偏移"] = {
            0,
            0,
            0,
        },
        ["缩放倍率"] = 1,
        ["施法音效"] = "",
        ["击中音效"] = "",
        ["震荡强度"] = 0,
        ["震荡时间"] = 0,
    },
}
-- --- AUTO GENERATED CONFIG END ---

return EffectTypeConfig
