-- GameModeConfig.lua
-- Generated by ConfigExporter. Any custom code will be overwritten.

---@class GameModeConfig
---@field Data table<string, table>

---@type GameModeConfig
local GameModeConfig = {Data = {}}

-- --- AUTO GENERATED CONFIG BEGIN ---
GameModeConfig.Data = {
    ['飞车挑战赛'] = {
      ['名字'] = '飞车挑战赛',
      ['玩法名称'] = '飞翔的荷兰人',
      ['玩法类型'] = '飞车',
      ['玩法描述'] = '飞翔的荷兰人',
      ['图标资源'] = '',
      ['玩法规则'] = {
        ['比赛时长'] = 60,
        ['准备时间'] = 10,
        ['入口节点'] = 'jump1',
        ['胜利条件'] = '胜利条件',
      },
    },
}
-- --- AUTO GENERATED CONFIG END ---

return GameModeConfig
