-- ItemTypeConfig.lua
-- Generated by ConfigExporter. Any custom code will be overwritten.

---@class ItemTypeConfig
---@field Data table<string, table>

---@type ItemTypeConfig
local ItemTypeConfig = {Data = {}}

-- --- AUTO GENERATED CONFIG BEGIN ---
ItemTypeConfig.Data = {
    ["加速卡"] = {
        ["名字"] = "加速卡",
        ["物品类型"] = "物品",
        ["描述"] = "",
        ["图标"] = "",
        ["品级"] = "普通",
        ["战力"] = 0,
        ["强化倍率"] = 0,
        ["强化材料增加倍率"] = 0,
        ["最大强化等级"] = 0,
        ["图鉴完成奖励数量"] = 0,
        ["图鉴高级完成奖励数量"] = 0,
        ["售出价格"] = 0,
        ["在背包里显示"] = true,
        ["货币序号"] = 0,
        ["获得音效"] = "",
        ["取消获得物品"] = false,
        ["获得执行指令"] = {
            "事实上大事",
        },
        ["使用执行指令"] = {
            "擦擦擦asd按时",
        },
        ["分解可得"] = {
            {
                ["物品"] = nil,
                ["数量"] = 0,
            },
        },
    },
}
-- --- AUTO GENERATED CONFIG END ---

return ItemTypeConfig
