-- LevelConfig.lua
-- Generated by ConfigExporter. Any custom code will be overwritten.

---@class LevelConfig
---@field Data table<string, table>

---@type LevelConfig
local LevelConfig = {Data = {}}

-- --- AUTO GENERATED CONFIG BEGIN ---
LevelConfig.Data = {
    ['飞车关卡初级'] = {
      ['名字'] = '飞车关卡初级',
      ['关卡名称'] = '飞车冲锋',
      ['默认玩法'] = '飞车挑战赛',
      ['最少人数'] = 1,
      ['最多人数'] = 8,
      ['玩法规则'] = {
        ['比赛时长'] = 30,
        ['准备时间'] = 10,
        ['胜利条件'] = '比赛时长结束',
      },
      ['基础奖励'] = {
        {
          ['奖励物品'] = '金币',
          ['计算方式'] = '公式计算',
          ['固定数量'] = 0,
          ['奖励公式'] = 'distance/100',
        },
      },
      ['排名奖励'] = {
        {
          ['名次'] = 1,
          ['奖励列表'] = {
            {
              ['物品'] = '金币',
              ['数量'] = 7,
            },
          },
        },
        {
          ['名次'] = 2,
          ['奖励列表'] = {
            {
              ['物品'] = '金币',
              ['数量'] = 5,
            },
          },
        },
      },
    },
}
-- --- AUTO GENERATED CONFIG END ---

return LevelConfig
