-- LevelConfig.lua
-- Generated by ConfigExporter. Any custom code will be overwritten.

---@class LevelConfig
---@field Data table<string, table>

---@type LevelConfig
local LevelConfig = {Data = {}}

-- --- AUTO GENERATED CONFIG BEGIN ---
LevelConfig.Data = {
    ['飞车关卡初级'] = {
      ['名字'] = '飞车关卡初级',
      ['关卡名称'] = '飞车冲锋',
      ['默认玩法'] = '飞车挑战赛',
      ['最少人数'] = 1,
      ['最多人数'] = 20,
      ['玩法规则'] = {
        ['比赛时长'] = 60,
        ['准备时间'] = 10,
        ['胜利条件'] = '比赛时长结束',
      },
      ['游戏开始指令'] = {
        'attribute { "操作类型": "仅加成新增", "属性名": "速度", "来源": "COMMAND", "玩家属性加成": [ { "名称": "数据_固定值_移动速度", "作用类型": "单独相加", "缩放倍率": 0 } ], "其他加成": [ "宠物", "伙伴", "尾迹", "翅膀" ] }',
      },
      ['游戏结算指令'] = {
        'attribute { "操作类型": "恢复", "属性名": "速度" }',
      },
      ['发送的变量'] = {
      },
      ['基础奖励'] = {
        {
          ['奖励物品'] = '金币',
          ['计算方式'] = '飞车挑战赛',
          ['奖励公式'] = 'distance/100',
        },
      },
      ['排名奖励'] = {
      },
      ['实时奖励规则'] = {
        {
          ['触发条件'] = 'distance>=30000',
          ['规则ID'] = 'distance3',
          ['奖励物品'] = '奖杯',
          ['奖励公式'] = 30,
        },
        {
          ['触发条件'] = 'distance>=50000',
          ['规则ID'] = 'distance5',
          ['奖励物品'] = '奖杯',
          ['奖励公式'] = 50,
        },
        {
          ['触发条件'] = 'distance>=100000',
          ['规则ID'] = 'distance6',
          ['奖励物品'] = '奖杯',
          ['奖励公式'] = 80,
        },
        {
          ['触发条件'] = 'distance>=130000',
          ['规则ID'] = 'distance13',
          ['奖励物品'] = '奖杯',
          ['奖励公式'] = 30,
        },
        {
          ['触发条件'] = 'distance>=150000',
          ['规则ID'] = 'distance15',
          ['奖励物品'] = '奖杯',
          ['奖励公式'] = 50,
        },
        {
          ['触发条件'] = 'distance>=200000',
          ['规则ID'] = 'distance20',
          ['奖励物品'] = '奖杯',
          ['奖励公式'] = 80,
        },
      },
    },
}
-- --- AUTO GENERATED CONFIG END ---

return LevelConfig
