-- RewardBonusConfig.lua
-- Generated by ConfigExporter. Any custom code will be overwritten.

---@class RewardBonusConfig
---@field Data table<string, table>

---@type RewardBonusConfig
local RewardBonusConfig = {Data = {}}

-- --- AUTO GENERATED CONFIG BEGIN ---
RewardBonusConfig.Data = {
    ['累计充值'] = {
      ['配置名称'] = '累计充值',
      ['描述'] = '',
      ['奖励类型'] = '累计充值',
      ['重置周期'] = '永不重置',
      ['计算方式'] = '迷你币',
      ['奖励列表'] = {
        {
          ['条件公式'] = '',
          ['消耗迷你币'] = 100,
          ['权重'] = 1,
          ['奖励物品列表'] = {
            {
              ['奖励类型'] = '物品',
              ['物品'] = '奖杯',
              ['翅膀配置'] = nil,
              ['宠物配置'] = nil,
              ['伙伴配置'] = nil,
              ['数量'] = 100,
              ['星级'] = 1,
            },
            {
              ['奖励类型'] = '物品',
              ['物品'] = '金币',
              ['翅膀配置'] = nil,
              ['宠物配置'] = nil,
              ['伙伴配置'] = nil,
              ['数量'] = 10000,
              ['星级'] = 1,
            },
            {
              ['奖励类型'] = '宠物',
              ['物品'] = nil,
              ['翅膀配置'] = nil,
              ['宠物配置'] = '咩咩糖糖',
              ['伙伴配置'] = nil,
              ['数量'] = 1,
              ['星级'] = 1,
            },
          },
        },
        {
          ['条件公式'] = '',
          ['消耗迷你币'] = 60,
          ['权重'] = 2,
          ['奖励物品列表'] = {
            {
              ['奖励类型'] = '物品',
              ['物品'] = '奖杯',
              ['翅膀配置'] = nil,
              ['宠物配置'] = nil,
              ['伙伴配置'] = nil,
              ['数量'] = 600,
              ['星级'] = 1,
            },
            {
              ['奖励类型'] = '物品',
              ['物品'] = '金币',
              ['翅膀配置'] = nil,
              ['宠物配置'] = nil,
              ['伙伴配置'] = nil,
              ['数量'] = 80000,
              ['星级'] = 1,
            },
            {
              ['奖励类型'] = '伙伴',
              ['物品'] = nil,
              ['翅膀配置'] = nil,
              ['宠物配置'] = nil,
              ['伙伴配置'] = '冥焰龙魂',
              ['数量'] = 2,
              ['星级'] = 1,
            },
          },
        },
      },
    },
}
-- --- AUTO GENERATED CONFIG END ---

return RewardBonusConfig
