-- SceneNodeConfig.lua
-- Generated by ConfigExporter. Any custom code will be overwritten.

---@class SceneNodeConfig
---@field Data table<string, table>

---@type SceneNodeConfig
local SceneNodeConfig = {Data = {}}

-- --- AUTO GENERATED CONFIG BEGIN ---
SceneNodeConfig.Data = {
    ['jump_plat'] = {
      ['名字'] = 'jump_plat',
      ['场景节点路径'] = 'Ground/init_map/Scene/jump_plat',
      ['场景类型'] = '跳台',
      ['音效资源'] = '',
      ['进入指令'] = '',
      ['离开指令'] = '',
      ['定时指令列表'] = {
      },
    },
}
-- --- AUTO GENERATED CONFIG END ---

return SceneNodeConfig
