-- SceneNodeConfig.lua
-- Generated by ConfigExporter. Any custom code will be overwritten.

---@class SceneNodeConfig
---@field Data table<string, table>

---@type SceneNodeConfig
local SceneNodeConfig = {Data = {}}

-- --- AUTO GENERATED CONFIG BEGIN ---
SceneNodeConfig.Data = {
    ['jump1'] = {
      ['名字'] = 'jump1',
      ['唯一ID'] = 'acd1a360-1a02-4406-b9ed-70f96a5a46a7',
      ['场景节点路径'] = 'Ground/init_map/terrain/Scene/jump_plat',
      ['场景类型'] = '飞行比赛',
      ['区域节点配置'] = {
        ['包围盒节点'] = 'jump1_TriggerBox',
        ['复活节点'] = 'BasicRespawn',
        ['传送节点'] = 'TeleportNode',
        ['比赛场景'] = 'Ground/init_map/terrain/Scene/race_track',
      },
      ['关联关卡'] = '飞车关卡初级',
      ['玩法规则'] = {
        ['比赛时长'] = 60,
        ['准备时间'] = 10,
        ['胜利条件'] = '比赛时长结束',
      },
      ['音效资源'] = '',
      ['进入指令'] = '',
      ['离开指令'] = '',
      ['定时指令列表'] = {
      },
    },
    ['挂机点1'] = {
      ['名字'] = '挂机点1',
      ['唯一ID'] = '6efb0be3-012f-4f82-aea3-03c6f985c1c2',
      ['场景节点路径'] = 'Ground/init_map/terrain/AutoSpot/左侧挂机点/挂机点1',
      ['场景类型'] = '挂机点',
      ['区域节点配置'] = {
        ['包围盒节点'] = 'TriggerBox',
        ['复活节点'] = '',
        ['传送节点'] = '',
        ['比赛场景'] = '',
      },
      ['关联关卡'] = nil,
      ['玩法规则'] = {
        ['比赛时长'] = 0,
        ['准备时间'] = 0,
        ['胜利条件'] = '比赛时长结束',
      },
      ['音效资源'] = '',
      ['进入指令'] = '',
      ['离开指令'] = '',
      ['定时指令列表'] = {
        {
          ['指令'] = 'variable { "操作类型": "新增",  "变量名": "数据_固定值_战力值", "数值": 100, "玩家变量加成": [ { "名称": "加成_百分比_训练加成", "作用类型": "单独相加" }, { "名称": "加成_百分比_双倍训练", "作用类型": "最终乘法" } ] }',
          ['间隔'] = 1,
        },
      },
    },
}
-- --- AUTO GENERATED CONFIG END ---

return SceneNodeConfig
