-- SceneNodeConfig.lua
-- Generated by ConfigExporter. Any custom code will be overwritten.

---@class SceneNodeConfig
---@field Data table<string, table>

---@type SceneNodeConfig
local SceneNodeConfig = {Data = {}}

-- --- AUTO GENERATED CONFIG BEGIN ---
SceneNodeConfig.Data = {
    ['jump1'] = {
      ['名字'] = 'jump1',
      ['唯一ID'] = 'acd1a360-1a02-4406-b9ed-70f96a5a46a7',
      ['场景节点路径'] = 'Ground/init_map/terrain/Scene/jump_plat',
      ['场景类型'] = '飞行比赛',
      ['区域节点配置'] = {
        ['包围盒节点'] = 'jump1_TriggerBox',
        ['复活节点'] = 'BasicRespawn',
        ['传送节点'] = 'TeleportNode',
        ['比赛场景'] = 'Ground/init_map/terrain/Scene/track',
      },
      ['关联关卡'] = '飞车关卡初级',
      ['玩法规则'] = {
        ['比赛时长'] = 60,
        ['准备时间'] = 10,
        ['胜利条件'] = '比赛时长结束',
      },
      ['音效资源'] = '',
      ['进入指令'] = '',
      ['离开指令'] = '',
      ['定时指令列表'] = {
      },
    },
}
-- --- AUTO GENERATED CONFIG END ---

return SceneNodeConfig
