-- SimulatorTalentConfig.lua
-- Generated by ConfigExporter. Any custom code will be overwritten.

---@class SimulatorTalentConfig
---@field Data table<string, table>

---@type SimulatorTalentConfig
local SimulatorTalentConfig = {Data = {}}

-- --- AUTO GENERATED CONFIG BEGIN ---
SimulatorTalentConfig.Data = {
    ['涅槃栏位'] = {
      ['名字'] = '涅槃栏位',
      ['排序'] = 1,
      ['类型'] = '栏位',
      ['最大等级'] = 10,
      ['消耗物品'] = {
        {
          ['物品'] = '奖杯',
          ['数量公式'] = '10',
        },
        {
          ['物品'] = '金币',
          ['数量公式'] = '10',
        },
      },
      ['加成倍率公式'] = '10',
    },
    ['飞行速度加成'] = {
      ['名字'] = '飞行速度加成',
      ['排序'] = 2,
      ['类型'] = '属性',
      ['最大等级'] = 10,
      ['消耗物品'] = {
        {
          ['物品'] = '奖杯',
          ['数量公式'] = '10',
        },
        {
          ['物品'] = '金币',
          ['数量公式'] = '10',
        },
      },
      ['加成倍率公式'] = 'LVL*2+10',
    },
}
-- --- AUTO GENERATED CONFIG END ---

return SimulatorTalentConfig
