-- TeleportPointConfig.lua
-- Generated by ConfigExporter. Any custom code will be overwritten.

---@class TeleportPointConfig
---@field Data table<string, table>

---@type TeleportPointConfig
local TeleportPointConfig = {Data = {}}

-- --- AUTO GENERATED CONFIG BEGIN ---
TeleportPointConfig.Data = {
    ['天穹巨鲸'] = {
      ['传送点名称'] = '天穹巨鲸',
      ['传送节点'] = 'Ground/map3/terrain/Teleport/传送点',
      ['场景节点'] = 'map3',
      ['需求条件'] = '600000000000000000000' --[[ Large Number: 600000000000000000000 ]],
      ['权重'] = 3,
      ['图片资源路径'] = 'sandboxId://FlyUi/迷你界面/传送UI/天穹巨鲸.png',
      ['传送点描述'] = '樱花岛之地',
      ['变量表达公式'] = '$数据_固定值_历史最大战力值$ >= 600000000000000000000',
      ['是否解锁'] = true,
      ['传送消耗'] = 0,
    },
    ['樱花海洋'] = {
      ['传送点名称'] = '樱花海洋',
      ['传送节点'] = 'Ground/init_map/terrain/Teleport/传送点',
      ['场景节点'] = 'init_map',
      ['需求条件'] = 0,
      ['权重'] = 1,
      ['图片资源路径'] = 'sandboxId://FlyUi/迷你界面/传送UI/樱花海洋.png',
      ['传送点描述'] = '樱花岛之地',
      ['变量表达公式'] = '$数据_固定值_历史最大战力值$ >= 0',
      ['是否解锁'] = true,
      ['传送消耗'] = 0,
    },
    ['科技空岛'] = {
      ['传送点名称'] = '科技空岛',
      ['传送节点'] = 'Ground/map2/terrain/Teleport/传送点',
      ['场景节点'] = 'map2',
      ['需求条件'] = 12000000000000,
      ['权重'] = 2,
      ['图片资源路径'] = 'sandboxId://FlyUi/迷你界面/传送UI/科技空岛.png',
      ['传送点描述'] = '樱花岛之地',
      ['变量表达公式'] = '$数据_固定值_历史最大战力值$ >= 12000000000000',
      ['是否解锁'] = true,
      ['传送消耗'] = 0,
    },
}
-- --- AUTO GENERATED CONFIG END ---

return TeleportPointConfig
