-- TeleportPointConfig.lua
-- Generated by ConfigExporter. Any custom code will be overwritten.

---@class TeleportPointConfig
---@field Data table<string, table>

---@type TeleportPointConfig
local TeleportPointConfig = {Data = {}}

-- --- AUTO GENERATED CONFIG BEGIN ---
TeleportPointConfig.Data = {
    ['天穹巨鲸'] = {
      ['传送点名称'] = '天穹巨鲸',
      ['传送节点'] = 'Ground/map3/terrain/ModelNode/传送点',
      ['需求等级'] = 40,
      ['权重'] = 3,
      ['图片资源路径'] = 'sandboxId://FlyUi/迷你界面/传送UI/天穹巨鲸.png',
      ['传送点描述'] = '樱花岛之地',
      ['是否解锁'] = true,
      ['传送消耗'] = 0,
    },
    ['樱花海洋'] = {
      ['传送点名称'] = '樱花海洋',
      ['传送节点'] = 'Ground/init_map/terrain/Teleport/传送点',
      ['需求等级'] = 0,
      ['权重'] = 1,
      ['图片资源路径'] = 'sandboxId://FlyUi/迷你界面/传送UI/樱花海洋.png',
      ['传送点描述'] = '樱花岛之地',
      ['是否解锁'] = true,
      ['传送消耗'] = 0,
    },
    ['科技空岛'] = {
      ['传送点名称'] = '科技空岛',
      ['传送节点'] = 'Ground/map2/terrain/ModelNode/传送点',
      ['需求等级'] = 20,
      ['权重'] = 2,
      ['图片资源路径'] = 'sandboxId://FlyUi/迷你界面/传送UI/科技空岛.png',
      ['传送点描述'] = '樱花岛之地',
      ['是否解锁'] = true,
      ['传送消耗'] = 0,
    },
}
-- --- AUTO GENERATED CONFIG END ---

return TeleportPointConfig
